package kedai;
// Generated Oct 22, 2020 9:02:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Acounts generated by hbm2java
 */
public class Acounts  implements java.io.Serializable {


     private String username;
     private String password;
     private String nama;
     private String role;
     private Set<Orderr> orderrs = new HashSet<Orderr>(0);

    public Acounts() {
    }

	
    public Acounts(String username, String password, String nama, String role) {
        this.username = username;
        this.password = password;
        this.nama = nama;
        this.role = role;
    }
    public Acounts(String username, String password, String nama, String role, Set<Orderr> orderrs) {
       this.username = username;
       this.password = password;
       this.nama = nama;
       this.role = role;
       this.orderrs = orderrs;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public Set<Orderr> getOrderrs() {
        return this.orderrs;
    }
    
    public void setOrderrs(Set<Orderr> orderrs) {
        this.orderrs = orderrs;
    }




}


