package kedai;
// Generated Oct 22, 2020 9:02:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private Long id;
     private String nama;
     private int harga;
     private String jenis;
     private Set<Orderdetails> orderdetailses = new HashSet<Orderdetails>(0);

    public Menu() {
    }

	
    public Menu(String nama, int harga, String jenis) {
        this.nama = nama;
        this.harga = harga;
        this.jenis = jenis;
    }
    public Menu(String nama, int harga, String jenis, Set<Orderdetails> orderdetailses) {
       this.nama = nama;
       this.harga = harga;
       this.jenis = jenis;
       this.orderdetailses = orderdetailses;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public int getHarga() {
        return this.harga;
    }
    
    public void setHarga(int harga) {
        this.harga = harga;
    }
    public String getJenis() {
        return this.jenis;
    }
    
    public void setJenis(String jenis) {
        this.jenis = jenis;
    }
    public Set<Orderdetails> getOrderdetailses() {
        return this.orderdetailses;
    }
    
    public void setOrderdetailses(Set<Orderdetails> orderdetailses) {
        this.orderdetailses = orderdetailses;
    }




}


