package kedai;
// Generated Oct 22, 2020 9:02:07 PM by Hibernate Tools 4.3.1

/**
 * Orderdetails generated by hbm2java
 */
public class Orderdetails implements java.io.Serializable {

    private Long id;
    private Menu menu;
    private Orderr orderr;
    private int jumlah;
    private String keterangan;
    private int idpesanan;
    private int subtotal;
    private String status;

    public Orderdetails() {
    }

    public Orderdetails(int idpesanan, Menu menu, int jumlah, String keterangan, int subtotal) {
        this.idpesanan = idpesanan;
        this.menu = menu;
        this.jumlah = jumlah;
        this.keterangan = keterangan;
        this.subtotal = subtotal;
    }

    public Orderdetails(Menu menu, Orderr orderr, int jumlah, String keterangan, String status) {
        this.menu = menu;
        this.orderr = orderr;
        this.jumlah = jumlah;
        this.keterangan = keterangan;
        this.status = status;
    }

    public int getIdpesanan() {
        return idpesanan;
    }

    public void setIdpesanan(int idpesanan) {
        this.idpesanan = idpesanan;
    }

    public int getSubtotal() {
        return subtotal;
    }

    public void setSubtotal(int subtotal) {
        this.subtotal = subtotal;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Menu getMenu() {
        return this.menu;
    }

    public void setMenu(Menu menu) {
        this.menu = menu;
    }

    public Orderr getOrderr() {
        return this.orderr;
    }

    public void setOrderr(Orderr orderr) {
        this.orderr = orderr;
    }

    public int getJumlah() {
        return this.jumlah;
    }

    public void setJumlah(int jumlah) {
        this.jumlah = jumlah;
    }

    public String getKeterangan() {
        return this.keterangan;
    }

    public void setKeterangan(String keterangan) {
        this.keterangan = keterangan;
    }
    
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

}
